#!/usr/bin/env bash
set -euo pipefail

# Embedded manifest data (extracted from previous update-docs.json)
skill_name="update-docs"
skill_description="Scans the repo to propose documentation and specification updates, writing docs/AUTOGEN_DOCS.md."
skill_entrypoint="docs.sh"

declare -A SKILL_META=( [name]="$skill_name" [description]="$skill_description" [entrypoint]="$skill_entrypoint" )

# Defaults
ALLOW_RUN=false
UPDATE_SPECS=true
MAX_TODOS=20
OUT_BASE="run/skills/update-docs"

usage() {
  cat <<EOF
Usage: $0 [--allow-run] [--no-update-specs] [--max-todos N] [--output json|text]
  --allow-run         allow safe --help invocations for scripts (no installs)
  --no-update-specs   do not write docs/specs files, only produce todos
  --max-todos N       maximum todos to write into todos.json (default $MAX_TODOS)
  --output            json or text (default text) - prints the report to stdout
EOF
}

timestamp() { date -u +%Y%m%dT%H%M%SZ; }

TS=$(timestamp)
OUT="$OUT_BASE/$TS"
RAW="$OUT/raw"
mkdir -p "$RAW"

capture_git_metadata() {
  git rev-parse --verify HEAD 2>/dev/null >"$RAW/head_sha.txt" || true
  git log -n 50 --pretty=format:'%h %an %ad %s' --date=iso >"$RAW/head_log.txt" 2>/dev/null || true
  git status --porcelain >"$RAW/git_status.txt" 2>/dev/null || true
}

collect_docs() {
  for f in README.md AGENT.md; do
    if [ -f "$f" ]; then
      head -n 400 "$f" >"$RAW/$(basename "$f")"
    fi
  done
  if [ -d docs ]; then
    find docs -maxdepth 2 -type f -print0 2>/dev/null | xargs -0 -I{} sh -c 'echo "== {} =="; head -n 200 "{}"' >"$RAW/docs_preview.txt" 2>/dev/null || true
  fi
  find . -path "./.git" -prune -o -type f -name "*.md" -print >"$RAW/markdown_files.txt" 2>/dev/null || true
}

collect_scripts() {
  find scripts -type f -print >"$RAW/script_files.txt" 2>/dev/null || true
  find scripts/skills -type f -print >"$RAW/skill_scripts.txt" 2>/dev/null || true
  find scripts -type f -print0 2>/dev/null | xargs -0 grep -InE "^#!.*(sh|bash|python|node|perl)" >"$RAW/shebangs.txt" 2>/dev/null || true
}

collect_src() {
  [ -d src ] && find src -type f -print >"$RAW/src_files.txt" 2>/dev/null || true
}

find_todos() {
  find . -path "./.git" -prune -o -type f -print0 2>/dev/null | xargs -0 grep -InE "TODO|FIXME" >"$RAW/todos.txt" 2>/dev/null || true
}

extract_top_comment() {
  file="$1"
  head -n 80 "$file" 2>/dev/null | awk 'BEGIN{ok=0} /^[[:space:]]*($|#|\/\/|\/\*)/{print; ok=1} ok && NF==0 {exit}' | sed -n '1,12p'
}

safe_help() {
  file="$1"
  if [ "$ALLOW_RUN" = "true" ] && [ -x "$file" ]; then
    # run short help with timeout if available; portable fallback when timeout missing
    if command -v timeout >/dev/null 2>&1; then
      (timeout 3 "$file" --help 2>/dev/null || timeout 3 "$file" -h 2>/dev/null) || true
    else
      # portable fallback: run help in background and kill after 3s
      ("$file" --help 2>/dev/null || "$file" -h 2>/dev/null) & pid=$!
      sleep 3
      if kill -0 "$pid" 2>/dev/null; then
        kill "$pid" 2>/dev/null || true
        sleep 0.1
        kill -9 "$pid" 2>/dev/null || true
      fi
      wait "$pid" 2>/dev/null || true
    fi
  fi
}

spec_path_for() {
  file="$1"
  rel=$(printf '%s' "$file" | sed 's|^\./||')
  spec="docs/specs/$rel"
  spec="${spec%.*}.md"
  printf '%s' "$spec"
}

generate_spec_for() {
  file="$1"
  spec=$(spec_path_for "$file")
  dir=$(dirname "$spec")
  mkdir -p "$dir"
  tmp="$spec.tmp"
  cat >"$tmp" <<-EOF
---
name: $(basename "$spec" .md)
generated_by: $0
generated_at: $(timestamp)
source: $file
autogenerated: true
---

EOF
  echo "## Purpose" >>"$tmp"
  extract_top_comment "$file" >>"$tmp" 2>/dev/null || true
  echo "" >>"$tmp"
  echo "## Synopsis / Usage" >>"$tmp"
  if [ -x "$file" ]; then
    safe_help "$file" >>"$tmp" 2>/dev/null || true
  fi
  echo "" >>"$tmp"
  echo "## Reference" >>"$tmp"
  echo "- Source: $file" >>"$tmp"

  if [ -f "$spec" ]; then
    if grep -q "autogenerated: true" "$spec" 2>/dev/null; then
      mv "$tmp" "$spec"
    else
      cp "$spec" "${spec}.bak" 2>/dev/null || true
      mv "$tmp" "$spec"
    fi
  else
    mv "$tmp" "$spec"
  fi
  printf '%s' "$spec"
}

generate_all_specs() {
  if [ -f "$RAW/script_files.txt" ]; then
    while IFS= read -r file; do
      [ -z "$file" ] && continue
      generate_spec_for "$file" >/dev/null || true
    done <"$RAW/script_files.txt"
  fi
  if [ -f "$RAW/src_files.txt" ]; then
    while IFS= read -r file; do
      [ -z "$file" ] && continue
      generate_spec_for "$file" >/dev/null || true
    done <"$RAW/src_files.txt"
  fi
}

build_todos() {
  todos_out="$OUT/todos.json"
  mkdir -p "$(dirname "$todos_out")"
  echo "[" >"$todos_out"
  first=1
  # missing specs for scripts
  if [ -f "$RAW/script_files.txt" ]; then
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      sp=$(spec_path_for "$f")
      if [ ! -f "$sp" ]; then
        id=$(printf 'add-spec-%s' "$(echo "$f" | sed 's|/|_|g;s/[^a-z0-9_-]//g')")
        title="Add spec for $f"
        desc="Create docs/specs entry documenting $f (purpose, usage, inputs, outputs, env)."
        ac='["Spec file exists at '$sp'","Includes PURPOSE and SYNOPSIS sections"]'
        complexity=2
        impact="medium"
        branch="docs/add-spec-$(echo "$f" | sed 's|/|_|g')"
        commit_msg="docs(specs): add spec for $f"
        obj=$(printf '{"id":"%s","title":"%s","description":"%s","files":["%s"],"acceptance_criteria":%s,"complexity":%d,"impact":"%s","priority":3,"suggested_branch":"%s","commit_msg":"%s"}' "$id" "$title" "$desc" "$f" "$ac" "$complexity" "$impact" "$branch" "$commit_msg")
        if [ $first -eq 0 ]; then echo "," >>"$todos_out"; fi
        echo -n "$obj" >>"$todos_out"
        first=0
      fi
    done <"$RAW/script_files.txt"
  fi
  # TODO/FIXME occurrences
  if [ -f "$RAW/todos.txt" ]; then
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      file=$(printf '%s' "$line" | cut -d: -f1)
      snippet=$(printf '%s' "$line" | cut -d: -f2- | sed 's/"/\\"/g' | sed 's/^ *//')
      id=$(printf 'fix-todo-%s' "$(echo "$file" | sed 's|/|_|g;s/[^a-z0-9_-]//g')")
      title="Address TODO in $file"
      desc="Resolve or document TODO/FIXME: $snippet"
      ac='["Updated source/doco addressing the TODO","Tests or docs updated accordingly"]'
      complexity=2
      impact="low"
      branch="chore/fix-todo-$(echo "$file" | sed 's|/|_|g')"
      commit_msg="chore(docs): address TODO in $file"
      obj=$(printf '{"id":"%s","title":"%s","description":"%s","files":["%s"],"acceptance_criteria":%s,"complexity":%d,"impact":"%s","priority":4,"suggested_branch":"%s","commit_msg":"%s"}' "$id" "$title" "$desc" "$file" "$ac" "$complexity" "$impact" "$branch" "$commit_msg")
      if [ $first -eq 0 ]; then echo "," >>"$todos_out"; fi
      echo -n "$obj" >>"$todos_out"
      first=0
    done <"$RAW/todos.txt"
  fi
  echo "]" >>"$todos_out"
}

write_report() {
  report_json="$OUT/report.json"
  mkdir -p "$(dirname "$report_json")"
  num_docs=$(wc -l <"$RAW/markdown_files.txt" 2>/dev/null || echo 0)
  num_scripts=$(wc -l <"$RAW/script_files.txt" 2>/dev/null || echo 0)
  num_src=$(wc -l <"$RAW/src_files.txt" 2>/dev/null || echo 0)
  num_todos=$(wc -l <"$RAW/todos.txt" 2>/dev/null || echo 0)
  cat >"$report_json" <<JSON
{
  "skill":"${SKILL_META[name]}",
  "timestamp":"$TS",
  "docs_found": $num_docs,
  "scripts_found": $num_scripts,
  "src_found": $num_src,
  "todo_occurrences": $num_todos
}
JSON
  cat >"$OUT/report.txt" <<TXT
Update-docs run at $TS
Docs found: $num_docs
Scripts found: $num_scripts
Source files found: $num_src
TODO/FIXME occurrences: $num_todos
Outputs: $OUT
TXT
}

main() {
  capture_git_metadata
  collect_docs
  collect_scripts
  collect_src
  find_todos
  if [ "$UPDATE_SPECS" = true ]; then
    generate_all_specs
  fi
  build_todos
  write_report
  echo "Wrote outputs to $OUT"
}

# Arg parsing
OUTPUT="text"
while [ $# -gt 0 ]; do
  case "$1" in
    --allow-run)
      ALLOW_RUN=true; shift ;;
    --no-update-specs)
      UPDATE_SPECS=false; shift ;;
    --max-todos)
      MAX_TODOS="$2"; shift 2 ;;
    --output)
      OUTPUT="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      shift ;;
  esac
done

main "$@"
