#!/usr/bin/env bash
set -euo pipefail

# Embedded manifest data (extracted from previous update-docs.json)
skill_name="update-docs"
skill_description="Scans the repo to propose documentation and specification updates, writing docs/AUTOGEN_DOCS.md."
skill_entrypoint="docs.sh"

declare -A SKILL_META=( [name]="$skill_name" [description]="$skill_description" [entrypoint]="$skill_entrypoint" )

# Defaults
ALLOW_RUN=false
UPDATE_SPECS=true
MAX_TODOS=20
OUT_BASE="run/skills/update-docs"

usage() {
  cat <<EOF
Usage: $0 [--allow-run] [--no-update-specs] [--max-todos N] [--output json|text]
  --allow-run         allow safe --help invocations for scripts (no installs)
  --no-update-specs   do not write docs/specs files, only produce todos
  --max-todos N       maximum todos to write into todos.json (default $MAX_TODOS)
  --output            json or text (default text) - prints the report to stdout
EOF
}

timestamp() { date -u +%Y%m%dT%H%M%SZ; }

TS=$(timestamp)
OUT="$OUT_BASE/$TS"
RAW="$OUT/raw"
mkdir -p "$RAW"

capture_git_metadata() {
  git rev-parse --verify HEAD 2>/dev/null >"$RAW/head_sha.txt" || true
  git log -n 50 --pretty=format:'%h %an %ad %s' --date=iso >"$RAW/head_log.txt" 2>/dev/null || true
  git status --porcelain >"$RAW/git_status.txt" 2>/dev/null || true
}

collect_docs() {
  for f in README.md AGENT.md; do
    if [ -f "$f" ]; then
      head -n 400 "$f" >"$RAW/$(basename "$f")"
    fi
  done
  if [ -d docs ]; then
    find docs -maxdepth 2 -type f -print0 2>/dev/null | xargs -0 -I{} sh -c 'echo "== {} =="; head -n 200 "{}"' >"$RAW/docs_preview.txt" 2>/dev/null || true
  fi
  find . -path "./.git" -prune -o -type f -name "*.md" -print >"$RAW/markdown_files.txt" 2>/dev/null || true
}

collect_scripts() {
  find scripts -type f -print >"$RAW/script_files.txt" 2>/dev/null || true
  find scripts/skills -type f -print >"$RAW/skill_scripts.txt" 2>/dev/null || true
  find scripts -type f -print0 2>/dev/null | xargs -0 grep -InE "^#!.*(sh|bash|python|node|perl)" >"$RAW/shebangs.txt" 2>/dev/null || true
}

collect_src() {
  [ -d src ] && find src -type f -print >"$RAW/src_files.txt" 2>/dev/null || true
}

find_todos() {
  find . -path "./.git" -prune -o -type f -print0 2>/dev/null | xargs -0 grep -InE "TODO|FIXME" >"$RAW/todos.txt" 2>/dev/null || true
}

extract_top_comment() {
  file="$1"
  head -n 80 "$file" 2>/dev/null | awk 'BEGIN{ok=0} /^[[:space:]]*($|#|\/\/|\/\*)/{print; ok=1} ok && NF==0 {exit}' | sed -n '1,12p'
}

safe_help() {
  file="$1"
  if [ "$ALLOW_RUN" = "true" ] && [ -x "$file" ]; then
    # run short help with timeout if available; portable fallback when timeout missing
    if command -v timeout >/dev/null 2>&1; then
      (timeout 3 "$file" --help 2>/dev/null || timeout 3 "$file" -h 2>/dev/null) || true
    else
      # portable fallback: run help in background and kill after 3s
      ("$file" --help 2>/dev/null || "$file" -h 2>/dev/null) & pid=$!
      sleep 3
      if kill -0 "$pid" 2>/dev/null; then
        kill "$pid" 2>/dev/null || true
        sleep 0.1
        kill -9 "$pid" 2>/dev/null || true
      fi
      wait "$pid" 2>/dev/null || true
    fi
  fi
}

spec_path_for() {
  file="$1"
  rel=$(printf '%s' "$file" | sed 's|^\./||')
  spec="docs/specs/$rel"
  spec="${spec%.*}.md"
  printf '%s' "$spec"
}

ensure_template() {
  template_dir="docs/specs"
  template_path="$template_dir/_template.md"
  if [ ! -d "$template_dir" ]; then
    mkdir -p "$template_dir"
  fi
  if [ ! -f "$template_path" ]; then
    cat >"$template_path" <<'TEMPLATE'
---
name: {{name}}
generated_by: {{generated_by}}
generated_at: {{generated_at}}
source: {{source}}
autogenerated: true
---

## Purpose
{{EXTRACT_TOP}}

## Synopsis / Usage
{{SAFE_HELP}}

## Reference
- Source: {{source}}
TEMPLATE
    echo "Created docs/specs/_template.md"
  fi
}

generate_spec_for() {
  file="$1"
  spec=$(spec_path_for "$file")
  dir=$(dirname "$spec")
  mkdir -p "$dir"
  tmp="$spec.tmp"

  template_path="docs/specs/_template.md"
  if [ -f "$template_path" ]; then
    name=$(basename "$spec" .md)
    gen_by=$(basename "$0")
    gen_at=$(timestamp)
    top_comment=$(extract_top_comment "$file" 2>/dev/null || true)
    help_output=""
    if [ -x "$file" ]; then
      help_output=$(safe_help "$file" 2>/dev/null || true)
    fi

    esc_name=$(printf '%s' "$name" | sed 's/[\/&]/\\&/g')
    esc_file=$(printf '%s' "$file" | sed 's/[\/&]/\\&/g')
    esc_gen_by=$(printf '%s' "$gen_by" | sed 's/[\/&]/\\&/g')
    esc_gen_at=$(printf '%s' "$gen_at" | sed 's/[\/&]/\\&/g')

    sed -e "s/{{name}}/$esc_name/g" -e "s/{{source}}/$esc_file/g" -e "s/{{generated_by}}/$esc_gen_by/g" -e "s/{{generated_at}}/$esc_gen_at/g" "$template_path" >"$tmp"

    # Inject multi-line content for extract_top_comment and safe_help
    awk -v top="$top_comment" -v help="$help_output" '{
      if (index($0, "{{EXTRACT_TOP}}")) {
        print top;
      } else if (index($0, "{{SAFE_HELP}}")) {
        print help;
      } else {
        print $0;
      }
    }' "$tmp" >"$tmp".1 && mv "$tmp".1 "$tmp"
  else
    cat >"$tmp" <<-EOF
---
name: $(basename "$spec" .md)
generated_by: $0
generated_at: $(timestamp)
source: $file
autogenerated: true
---

EOF
    echo "## Purpose" >>"$tmp"
    extract_top_comment "$file" >>"$tmp" 2>/dev/null || true
    echo "" >>"$tmp"
    echo "## Synopsis / Usage" >>"$tmp"
    if [ -x "$file" ]; then
      safe_help "$file" >>"$tmp" 2>/dev/null || true
    fi
    echo "" >>"$tmp"
    echo "## Reference" >>"$tmp"
    echo "- Source: $file" >>"$tmp"
  fi

  if [ -f "$spec" ]; then
    if grep -q "autogenerated: true" "$spec" 2>/dev/null; then
      mv "$tmp" "$spec"
    else
      cp "$spec" "${spec}.bak" 2>/dev/null || true
      mv "$tmp" "$spec"
    fi
  else
    mv "$tmp" "$spec"
  fi
  printf '%s' "$spec"
}

generate_all_specs() {
  if [ -f "$RAW/script_files.txt" ]; then
    while IFS= read -r file; do
      [ -z "$file" ] && continue
      generate_spec_for "$file" >/dev/null || true
    done <"$RAW/script_files.txt"
  fi
  if [ -f "$RAW/src_files.txt" ]; then
    while IFS= read -r file; do
      [ -z "$file" ] && continue
      generate_spec_for "$file" >/dev/null || true
    done <"$RAW/src_files.txt"
  fi
}

build_todos() {
  todos_out="$OUT/todos.json"
  mkdir -p "$(dirname "$todos_out")"
  echo "[" >"$todos_out"
  first=1
  # missing specs for scripts
  if [ -f "$RAW/script_files.txt" ]; then
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      sp=$(spec_path_for "$f")
      if [ ! -f "$sp" ]; then
        id=$(printf 'add-spec-%s' "$(echo "$f" | sed 's|/|_|g;s/[^a-z0-9_-]//g')")
        title="Add spec for $f"
        desc="Create docs/specs entry documenting $f (purpose, usage, inputs, outputs, env)."
        ac='["Spec file exists at '$sp'","Includes PURPOSE and SYNOPSIS sections"]'
        complexity=2
        impact="medium"
        branch="docs/add-spec-$(echo "$f" | sed 's|/|_|g')"
        commit_msg="docs(specs): add spec for $f"
        obj=$(printf '{"id":"%s","title":"%s","description":"%s","files":["%s"],"acceptance_criteria":%s,"complexity":%d,"impact":"%s","priority":3,"suggested_branch":"%s","commit_msg":"%s"}' "$id" "$title" "$desc" "$f" "$ac" "$complexity" "$impact" "$branch" "$commit_msg")
        if [ $first -eq 0 ]; then echo "," >>"$todos_out"; fi
        echo -n "$obj" >>"$todos_out"
        first=0
      fi
    done <"$RAW/script_files.txt"
  fi
  # TODO/FIXME occurrences
  if [ -f "$RAW/todos.txt" ]; then
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      file=$(printf '%s' "$line" | cut -d: -f1)
      snippet=$(printf '%s' "$line" | cut -d: -f2- | sed 's/"/\\"/g' | sed 's/^ *//')
      id=$(printf 'fix-todo-%s' "$(echo "$file" | sed 's|/|_|g;s/[^a-z0-9_-]//g')")
      title="Address TODO in $file"
      desc="Resolve or document TODO/FIXME: $snippet"
      ac='["Updated source/doco addressing the TODO","Tests or docs updated accordingly"]'
      complexity=2
      impact="low"
      branch="chore/fix-todo-$(echo "$file" | sed 's|/|_|g')"
      commit_msg="chore(docs): address TODO in $file"
      obj=$(printf '{"id":"%s","title":"%s","description":"%s","files":["%s"],"acceptance_criteria":%s,"complexity":%d,"impact":"%s","priority":4,"suggested_branch":"%s","commit_msg":"%s"}' "$id" "$title" "$desc" "$file" "$ac" "$complexity" "$impact" "$branch" "$commit_msg")
      if [ $first -eq 0 ]; then echo "," >>"$todos_out"; fi
      echo -n "$obj" >>"$todos_out"
      first=0
    done <"$RAW/todos.txt"
  fi
  echo "]" >>"$todos_out"
}

write_report() {
  report_json="$OUT/report.json"
  mkdir -p "$(dirname "$report_json")"
  if [ -f "$RAW/markdown_files.txt" ]; then
    num_docs=$(wc -l <"$RAW/markdown_files.txt" 2>/dev/null || echo 0)
  else
    num_docs=0
  fi
  if [ -f "$RAW/script_files.txt" ]; then
    num_scripts=$(wc -l <"$RAW/script_files.txt" 2>/dev/null || echo 0)
  else
    num_scripts=0
  fi
  if [ -f "$RAW/src_files.txt" ]; then
    num_src=$(wc -l <"$RAW/src_files.txt" 2>/dev/null || echo 0)
  else
    num_src=0
  fi
  if [ -f "$RAW/todos.txt" ]; then
    num_todos=$(wc -l <"$RAW/todos.txt" 2>/dev/null || echo 0)
  else
    num_todos=0
  fi
  cat >"$report_json" <<JSON
{
  "skill":"${SKILL_META[name]}",
  "timestamp":"$TS",
  "docs_found": $num_docs,
  "scripts_found": $num_scripts,
  "src_found": $num_src,
  "todo_occurrences": $num_todos
}
JSON
  cat >"$OUT/report.txt" <<TXT
Update-docs run at $TS
Docs found: $num_docs
Scripts found: $num_scripts
Source files found: $num_src
TODO/FIXME occurrences: $num_todos
Outputs: $OUT
TXT
}

build_guide() {
  out_md="${1:-$OUT/guide/compiled_guide.md}"
  out_dir="$(dirname "$out_md")"
  mkdir -p "$out_dir"
  : >"$out_md"

  printf '# Project Design & User Guide\n\n' >>"$out_md"

  if [ -f README.md ]; then
    printf '## README\n\n' >>"$out_md"
    sed -n '1,200p' README.md >>"$out_md" || true
    printf '\n\n' >>"$out_md"
  fi

  if [ -d docs ]; then
    find docs -type f -name '*.md' | sort | while IFS= read -r f; do
      base=$(basename "$f")
      [ "$base" = "_template.md" ] && continue
      printf '\n\n---\n\n' >>"$out_md"
      title=$(grep -m1 '^#' "$f" 2>/dev/null | sed 's/^#* *//')
      if [ -z "$title" ]; then
        title="$f"
      fi
      printf '## %s\n\n' "$title" >>"$out_md"
      cat "$f" >>"$out_md" || true
    done
  fi

  if [ -d docs/specs ]; then
    find docs/specs -type f -name '*.md' | sort | while IFS= read -r f; do
      base=$(basename "$f")
      [ "$base" = "_template.md" ] && continue
      printf '\n\n---\n\n' >>"$out_md"
      if grep -q '^name:' "$f" 2>/dev/null; then
        name=$(grep '^name:' "$f" | head -n1 | sed 's/^name:[[:space:]]*//')
      else
        name=$(basename "$f")
      fi
      printf '## %s\n\n' "$name" >>"$out_md"
      if sed -n '1,1p' "$f" | grep -q '^---'; then
        awk 'BEGIN{skip=0} NR==1 && /^---/ {skip=1; next} skip==1 && /^---/ {skip=0; next} skip==1 {next} {print}' "$f" >>"$out_md" || true
      else
        cat "$f" >>"$out_md" || true
      fi
    done
  fi

  printf '%s' "$out_md"
}

main() {
  mkdir -p "$OUT" "$RAW"
  capture_git_metadata
  collect_docs
  collect_scripts
  collect_src
  find_todos
  if [ "$UPDATE_SPECS" = true ]; then
    ensure_template
    generate_all_specs
  fi
  build_todos
  write_report
  echo "Wrote outputs to $OUT"
}

# Handle 'build' subcommand to compile docs and render PDF
if [ "${1:-}" = "build" ]; then
  shift
  mkdir -p "$OUT" "$RAW"
  capture_git_metadata
  collect_docs
  collect_scripts
  collect_src
  find_todos
  if [ "$UPDATE_SPECS" = true ]; then
    ensure_template
    generate_all_specs || true
  fi
  guide_md_default="$OUT/guide/compiled_guide.md"
  guide_md=$(build_guide "$guide_md_default")
  echo "Compiled guide: $guide_md"
  guide_pdf="$OUT/guide/guide.pdf"
  if command -v pandoc >/dev/null 2>&1; then
    pandoc "$guide_md" -s -o "$guide_pdf" 2>"$OUT/guide/pandoc.err" || true
    echo "Generated PDF: $guide_pdf"
  else
    echo "pandoc not found; PDF generation skipped" >"$OUT/guide/pandoc.err"
  fi
  exit 0
fi

# Arg parsing
OUTPUT="text"
while [ $# -gt 0 ]; do
  case "$1" in
    --allow-run)
      ALLOW_RUN=true; shift ;;
    --no-update-specs)
      UPDATE_SPECS=false; shift ;;
    --max-todos)
      MAX_TODOS="$2"; shift 2 ;;
    --output)
      OUTPUT="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      shift ;;
  esac
done

main "$@"
